---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: govc
  type: github-release
  source:
    user: vmware
    repository: govmomi
    access_token: ((github_token)) ## Optional: Removing this will cause you to hit the rate limit
- name: tasks-repo
  type: git
  source:
    uri: ((github_repo))
    branch: ((github_branch))
    username: ((github_username))
    password: ((github_token))
- name: custom-docker-image
  type: docker-image
  source:
    repository: rjain/buildbox

jobs:
- name: install-appliance
  plan:
  - in_parallel:
    - get: tasks-repo
    - get: govc
      params:
        globs:
        - "*Linux_x86_64*"
    - get: custom-docker-image

  - task: deploy-iris
    image: custom-docker-image  
    file: tasks-repo/tasks/import-appliance/task.yml
    params:
      GOVC_INSECURE: 1
      GOVC_URL: ((vcenter_host))
      GOVC_USERNAME: ((vcenter_usr))
      GOVC_PASSWORD: ((vcenter_pwd))
      GOVC_DATACENTER: ((vcenter_data_center))
      GOVC_DATASTORE: ((vcenter_data_store))
      GOVC_NETWORK: ((vcenter_network))
      GOVC_RESOURCE_POOL: ((vcenter_resource_pool))
      APPLIANCE_OVA_LOCATION: ((appliance_ova_location))
      APPLIANCE_SETTINGS: ((appliance_settings))

- name: delete-and-redeploy-appliance
  plan:
  - in_parallel:
    - get: tasks-repo
    - get: govc
      params:
        globs:
        - "*Linux_x86_64*"
    - get: custom-docker-image

  - task: delete-iris
    image: custom-docker-image  
    file: tasks-repo/tasks/delete-appliance/task.yml
    params:
      GOVC_INSECURE: 1
      GOVC_URL: ((vcenter_host))
      GOVC_USERNAME: ((vcenter_usr))
      GOVC_PASSWORD: ((vcenter_pwd))
      GOVC_DATACENTER: ((vcenter_data_center))
      GOVC_DATASTORE: ((vcenter_data_store))
      GOVC_NETWORK: ((vcenter_network))
      GOVC_RESOURCE_POOL: ((vcenter_resource_pool))
      APPLIANCE_OVA_LOCATION: ((appliance_ova_location))
      APPLIANCE_SETTINGS: ((appliance_settings))

  - task: deploy-iris
    image: custom-docker-image  
    file: tasks-repo/tasks/import-appliance/task.yml
    params:
      GOVC_INSECURE: 1
      GOVC_URL: ((vcenter_host))
      GOVC_USERNAME: ((vcenter_usr))
      GOVC_PASSWORD: ((vcenter_pwd))
      GOVC_DATACENTER: ((vcenter_data_center))
      GOVC_DATASTORE: ((vcenter_data_store))
      GOVC_NETWORK: ((vcenter_network))
      GOVC_RESOURCE_POOL: ((vcenter_resource_pool))
      APPLIANCE_OVA_LOCATION: ((appliance_ova_location))
      APPLIANCE_SETTINGS: ((appliance_settings))