---

platform: linux

params:
  GOVC_INSECURE:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_DATACENTER:
  GOVC_DATASTORE:
  GOVC_NETWORK:
  GOVC_RESOURCE_POOL:
  APPLIANCE_SETTINGS:
  APPLIANCE_OVA_LOCATION:

inputs:
  - name: tasks-repo
  - name: govc

run:
  path: tasks-repo/tasks/import-appliance/task.sh